version: 2
updates:
  - package-ecosystem: terraform
    directory: "/api/terraform/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "/api/terraform/python/layer_genai/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/api/terraform/python/"
    schedule:
      interval: "daily"
