version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/api/terraform/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "pip"
    directory: "/api/terraform/python/layer_genai/"
    schedule:
      interval: "daily"
    versioning-strategy: "auto"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "auto"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    versioning-strategy: "auto"
    reviewers:
      - "lpm0073"
