version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/api/terraform/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "pip"
    directory: "/api/terraform/python/layer_genai/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
      - "automated pr"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
      - "automated pr"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "npm"
    directory: "/client"
    labels:
      - "dependencies"
      - "javascript"
      - "automated pr"
    schedule:
      interval: "weekly"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependencies"
      - "javascript"
      - "automated pr"
    schedule:
      interval: "weekly"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "automated pr"
    schedule:
      interval: "weekly"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
