name: Check Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: main
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
