#------------------------------------------------------------------------------
# Lawrence McDaniel - https://lawrencemcdaniel.com
# Version Bump Workflow
#
# Used mostly to propagate Dependabot pushed to main to the next branch. Use
# cases:
# - Dependabot pushes to main
# - Manual push to main
# - back propagation of modifications to __version__.py
#------------------------------------------------------------------------------
  name: Merge main into next

  on:
    workflow_dispatch:
    push:
      branches:
        - main

  jobs:
    merge:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            persist-credentials: false

        - name: Merge main into next
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git checkout main
            git pull
            git checkout next
            git merge main
            git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git HEAD:next
          env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
