name: Python Unit Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.py"
  push:
    paths:
      - "**.py"

env:
  python-version: "3.11"

jobs:
  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Python tests
        uses: ./.github/actions/tests/python
        with:
          python-version: "${{ env.python-version}}"
          openai-api-organization: "${{ secrets.OPENAI_API_ORGANIZATION }}"
          openai-api-key: "${{ secrets.OPENAI_API_KEY }}"
          pinecone-api-key: "${{ secrets.PINECONE_API_KEY }}"
          pinecone-environment: "${{ secrets.PINECONE_ENVIRONMENT }}"
