# -----------------------------------------------------------------------------
# pre-commit tests
# -----------------------------------------------------------------------------
name: Test pre-commit rules

on: [workflow_dispatch]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Run pre-commit
        run: pre-commit run --all-files
