name: Python Unit Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.py"
  push:
    branches:
      - main
      - next
    paths:
      - "**.py"

env:
  python-version: "3.11"

jobs:
  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get IAM user info
        run: |
          aws sts get-caller-identity | sed -E 's/(arn:aws:iam::)[0-9]+(:user\/\w+)/\1************\2/' | jq '.Account="************"'

      - name: Run Python tests
        uses: ./.github/actions/tests/python
        with:
          python-version: "${{ env.python-version}}"
          google-maps-api-key: "${{ secrets.GOOGLE_MAPS_API_KEY }}"
          openai-api-organization: "${{ secrets.OPENAI_API_ORGANIZATION }}"
          openai-api-key: "${{ secrets.OPENAI_API_KEY }}"
          pinecone-api-key: "${{ secrets.PINECONE_API_KEY }}"
          pinecone-environment: "${{ secrets.PINECONE_ENVIRONMENT }}"
