#---------------------------------------------------------
# - Setup AWS CLI environment using the secrets from this repo.
# - Try to build and upload the image.
#---------------------------------------------------------
name: Test this action

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # required antecedent
      - uses: actions/checkout@v3.5.2

      # required antecedent
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # This action
      - name: Use the action in this repo to add a theme to an openedx build
        uses: ./
        with:
          repository: 'edx.custom-theme'
          repository-ref: 'master'
          repository-organization: lpm0073
