# -----------------------------------------------------------------------------
# Terraform Tests
#
# This workflow will run tests on the Terraform code located in ./api/terraform/
#
# Notes:
# - pull_request_target is used instead of pull_request because the
#   pull_request_target event behaves in an almost identical way to the
#   pull_request event, however, t runs in the context of the base repository of the
#   pull request rather than in the merge commit. This means that you have
#   access to Github Organization secrets when the workflow is triggered by
#   a pull_request_target event.
#
# - optionally add `if: github.actor != 'dependabot[bot]'` to the terraform-tests job to
#   prevent dependabot from running tests
# -----------------------------------------------------------------------------
  name: Test Terraform

  on: [workflow_dispatch]

  jobs:
    test-terraform:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v1

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Create lambda_dist_pkg directory
          run: |
            mkdir -p api/terraform/python/lambda_langchain/lambda_dist_pkg/

        - name: Terraform Init
          run: |
            cd api/terraform
            terraform init

        - name: Terraform Validate
          run: |
            cd api/terraform
            terraform validate

        - name: Terraform Plan
          run: |
            cd api/terraform
            terraform plan

        - name: Terraform Format
          run: |
            cd api/terraform
            terraform fmt -check
